[package]
name = "mfg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "parsec",
]

[dependencies]
parsec = { path = "./parsec" }
